package mx.dev.franco.automusictagfixer.common;

public enum Action {
    NONE,
    RETRY_IDENTIFICATION,
    SUCCESS_IDENTIFICATION,
    CANCELLED_IDENTIFICATION,
    RETRY_ON_ERROR,

    SUCCESS_TAGS_APPLIED,
    ERROR_TAGS_APPLIED,
    SUCCESS_RENAMING,
    ERROR_RENAMING,
    SUCCESS_UPDATING_COVER,
    ERROR_UPDATING_COVER,

    URI_ERROR
}
