package mx.dev.franco.automusictagfixer.services;

enum FixerState {
    STARTING_FETCHING_TRACKS,
    FINISHED_FETCHING_TRACKS,
    STARTING_FETCHING_TRACK_INFO,
    FINISHED_FETCHING_TRACK_INFO,
    STARTING_IDENTIFYING,
    FINISHED_IDENTIFYING,
    ERROR_IDENTIFYING,
    CANCELLED_IDENTIFYING,
    STARTING_FIXING,
    ERROR_FIXING,
    CANCELLED_FIXING,
    FINISHED_FIXING,
    STARTING_RENAMING,
    ERROR_RENAMING,
    CANCELLED_RENAMING,
    FINISHED_RENAMING,
    CANCELLED
}
